appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
travis:
  secure:
    BINSTAR_TOKEN: uQbtNtp+OxV5SVGvOq26g/i9tLJtEvZfcIhRXSCG1jRhFqOjWW7IgrA7N3EIlJLJEDnPhlapNw/+YPyhIXJkKOGhlPqhA5Edr0sLj4NN04+DVQJX7aStbs6y/BWZhPyU0TVfc1AwZr2b8kj7hI65djBe5jjjuSGk2Eygwha3MymAvmxg0iVQt56QfhA2dDH5vg842qUvMp/h55bXBVdDIAvFKsI5oVVfZU+rQHrAx5Ewa9UU/auAgmarJNc/P9WVCRd2uOeV3LLTOSbdr0Y5IUK1RNR+znYDr8rPcBPBfWtQ1iK6J1CEd+Yv4iq+FuJDHjuhBm36cDBuonfWWEs3KuMQhBWxCt+G3AH52/DhCEWR5sPV6UKfC7Q2DoVjOaIShtQiv2CVqyDPy/7UiUWwBAqXjfpFDt1uL7T+4s4N4uX0j3EhT2Z2hL1JpWDzl4QxkWn17OLSVhwU89zBgQMNf9hXMJ28pgHyFOr9aMWHCBTqRcx/OJ5eEstr6kIbUmkwm2RGEDMGxB9pQVKPuo5VYVtpeNaxYi9dOitGgq+4dQrZrHb5FIBF+SPH3pwnek0W0swKbc23OnoN23tfzAZC7UZvEKagp3X7hx9Tyl2RXsKA09N7Lntpr/TXr50xS0ZU2xuOEfkqfo7u4ExTuqy8K13DJ+ofuRRcBcaOnnXUC1s=
